# See https://help.github.com/articles/about-pull-requests/
branch:
  # Main branch
  main:
    # Require PR approval before merge
    required_approvals: 1
    # Dismiss stale PR approvals when new commits are pushed
    dismiss_stale_reviews: true
    # Require review from CODEOWNERS
    required_reviewers: []
    # Limit the number of reviewers for a PR
    limit: 2
    # Disallow automatic approval on PRs from codeowners
    require_code_owner_reviews: false

# Restrict deletions to main branch
delete:
  branches:
    - main

# Restrict force pushes to all branches
force_pushes:
  delete: true